In [62]:
%reload_ext autoreload
%autoreload 2

In [63]:
import numpy as np
import gym

from genetic import Agent

np.set_printoptions(precision=2)

# A first, simple, example

In [9]:
env = gym.make('CartPole-v0')

agent = Agent()

for i_episode in range(1):
    observation = env.reset()
    for t in range(100):
        #env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        print((action, reward))
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

[2017-11-20 22:46:10,474] Making new env: CartPole-v0


[-0.03 -0.04  0.02 -0.02]
(0, 1.0)
[-0.03 -0.23  0.02  0.28]
(1, 1.0)
[-0.03 -0.04  0.03 -0.01]
(1, 1.0)
[-0.03  0.16  0.03 -0.29]
(0, 1.0)
[-0.03 -0.04  0.02  0.01]
(1, 1.0)
[-0.03  0.16  0.02 -0.28]
(1, 1.0)
[-0.03  0.35  0.01 -0.57]
(1, 1.0)
[-0.02  0.55  0.   -0.85]
(1, 1.0)
[-0.01  0.74 -0.01 -1.15]
(1, 1.0)
[ 0.01  0.94 -0.04 -1.44]
(1, 1.0)
[ 0.02  1.13 -0.07 -1.75]
(1, 1.0)
[ 0.05  1.33 -0.1  -2.06]
(0, 1.0)
[ 0.07  1.13 -0.14 -1.8 ]
(0, 1.0)
[ 0.1   0.94 -0.18 -1.55]
(1, 1.0)
[ 0.11  1.14 -0.21 -1.9 ]
(0, 1.0)
Episode finished after 15 timesteps


In [71]:
agent = Agent(.5, verbose=True)

In [72]:
agent.weights1

array([[  1.32e-01,   7.36e-02,   2.52e-01,  -4.31e-03],
       [ -8.12e-01,   4.49e-02,  -5.64e-01,  -3.54e-01],
       [ -2.57e-04,   4.81e-01,   4.62e-01,  -1.24e-02],
       [  1.42e-01,   2.77e-01,   1.80e-02,   5.03e-01]])

In [73]:
agent.bias1

array([ 0.1,  0.1,  0.1,  0.1])

In [74]:
agent.weights2

array([[-0.33, -0.53, -0.6 , -0.67],
       [ 1.01,  0.53, -1.56, -0.59]])

In [75]:
agent.bias2

array([ 0.1,  0.1])

In [76]:
agent.action(observation)

[ 0.03  0.66  0.36 -0.57]
[ 0.13  0.76  0.46 -0.47]
[ 0.13  0.76  0.46  0.  ]
[-0.72 -0.18]
[-0.62 -0.08]


1

In [77]:
agent.copy()