In [562]:
%reload_ext autoreload
%autoreload 2

In [563]:
import numpy as np
import gym

from genetic import Agent, Generation

import time

np.set_printoptions(precision=0)

# A first, simple, example

In [564]:
env = gym.make('CartPole-v0')

for i_episode in range(10):
    observation = env.reset()
    
    for t in range(1000):
#         env.render()
        #print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
#         print((action, reward))
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

[2017-11-30 01:09:18,305] Making new env: CartPole-v0


Episode finished after 12 timesteps
Episode finished after 11 timesteps
Episode finished after 27 timesteps
Episode finished after 17 timesteps
Episode finished after 13 timesteps
Episode finished after 17 timesteps
Episode finished after 22 timesteps
Episode finished after 13 timesteps
Episode finished after 15 timesteps
Episode finished after 23 timesteps


# Avec un agent piloté par un réseau de neurones

In [569]:
agent = Agent(.5, verbose=False)

In [570]:
env = gym.make('CartPole-v0')

for i_episode in range(10):
    observation = env.reset()
    
    for t in range(1000):
#         env.render()
        #print(observation)
        action = agent.action(observation)
        observation, reward, done, info = env.step(action)
#         print((action, reward))
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

[2017-11-30 01:10:46,226] Making new env: CartPole-v0


Episode finished after 10 timesteps
Episode finished after 10 timesteps
Episode finished after 10 timesteps
Episode finished after 9 timesteps
Episode finished after 10 timesteps
Episode finished after 9 timesteps
Episode finished after 10 timesteps
Episode finished after 10 timesteps
Episode finished after 9 timesteps
Episode finished after 9 timesteps


# Algorithme génétique simple

In [576]:
generation = Generation(10)

[2017-11-30 01:12:35,822] Making new env: CartPole-v0


In [577]:
generation.reset()
generation.simulation_step()

array([ 11.,  10.,  10.,   9.,  23.,  18.,  10.,  10.,  18.,  10.])

Entraînement des agents :

In [578]:
for i in range(1000):
    
    generation.select(std=.1, proportion=.3)
    generation.reset()
    res = generation.simulation_step(300)
    
    print(str(i) + ': ' + str(np.sort(res)[-1:0:-1]), end='\r')
    
    if res.min() > 190:
        break

In [579]:
l = np.zeros(10)
agent = generation.agents[0]

for _ in range(100):
    generation.reset()
    res = generation.simulation_step(200)
    print(res, end='\r')
    l += res/100

print()
print(l)

[ 200.  200.  200.  200.  200.  200.  200.  200.  200.  200.]
[ 200.  200.  200.  200.  191.  200.  200.  200.  200.  200.]
