In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import numpy as np

import gym

# A first, simple, example

In [5]:
env = gym.make('CartPole-v0')

for i_episode in range(1):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        print((action, reward))
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

[2017-11-20 20:03:24,017] Making new env: CartPole-v0


[ 0.02340566  0.0449172  -0.01606675  0.03493236]
(0, 1.0)
[ 0.024304   -0.14997071 -0.01536811  0.32250307]
(1, 1.0)
[ 0.02130459  0.04536667 -0.00891804  0.02501355]
(1, 1.0)
[ 0.02221192  0.24061537 -0.00841777 -0.27046973]
(1, 1.0)
[ 0.02702423  0.43585643 -0.01382717 -0.56579573]
(0, 1.0)
[ 0.03574136  0.24093116 -0.02514308 -0.27750084]
(1, 1.0)
[ 0.04055998  0.43640262 -0.0306931  -0.57800664]
(0, 1.0)
[ 0.04928803  0.24172399 -0.04225323 -0.29514859]
(1, 1.0)
[ 0.05412251  0.43742206 -0.0481562  -0.60085244]
(0, 1.0)
[ 0.06287095  0.24300568 -0.06017325 -0.3237184 ]
(1, 1.0)
[ 0.06773107  0.43893052 -0.06664762 -0.63475403]
(1, 1.0)
[ 0.07650968  0.63491569 -0.0793427  -0.94765901]
(1, 1.0)
[ 0.08920799  0.83101118 -0.09829588 -1.26417916]
(0, 1.0)
[ 0.10582821  0.63727339 -0.12357946 -1.00382775]
(1, 1.0)
[ 0.11857368  0.83380997 -0.14365602 -1.33262434]
(0, 1.0)
[ 0.13524988  0.6407615  -0.17030851 -1.08812421]
(0, 1.0)
[ 0.14806511  0.44824394 -0.19207099 -0.85335473]
(1, 1.