In [62]:
%reload_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import gym

from genetic import Agent, Generation

import time

np.set_printoptions(precision=2)

# A first, simple, example

In [4]:
env = gym.make('CartPole-v0')

for i_episode in range(10):
    observation = env.reset()
    
    for t in range(1000):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        print((action, reward))
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

[2017-11-20 23:57:39,936] Making new env: CartPole-v0


[-0.02 -0.04 -0.02  0.01]
(0, 1.0)
[-0.02 -0.23 -0.02  0.3 ]
(1, 1.0)
[-0.03 -0.04 -0.02 -0.  ]
(1, 1.0)
[-0.03  0.16 -0.02 -0.3 ]
(0, 1.0)
[-0.02 -0.04 -0.02 -0.01]
(1, 1.0)
[-0.02  0.16 -0.02 -0.31]
(1, 1.0)
[-0.02  0.35 -0.03 -0.61]
(1, 1.0)
[-0.01  0.55 -0.04 -0.91]
(1, 1.0)
[-0.    0.75 -0.06 -1.22]
(1, 1.0)
[ 0.01  0.94 -0.08 -1.53]
(1, 1.0)
[ 0.03  1.14 -0.11 -1.84]
(1, 1.0)
[ 0.05  1.33 -0.15 -2.17]
(0, 1.0)
[ 0.08  1.14 -0.19 -1.93]
(0, 1.0)
Episode finished after 13 timesteps
[ 0.05 -0.02 -0.01  0.01]
(1, 1.0)
[ 0.05  0.18 -0.01 -0.29]
(0, 1.0)
[ 0.05 -0.02 -0.01  0.  ]
(0, 1.0)
[ 0.05 -0.21 -0.01  0.29]
(0, 1.0)
[ 0.05 -0.41 -0.01  0.58]
(0, 1.0)
[ 0.04 -0.6   0.    0.87]
(0, 1.0)
[ 0.03 -0.8   0.02  1.16]
(1, 1.0)
[ 0.01 -0.6   0.05  0.88]
(0, 1.0)
[  4.72e-04  -7.97e-01   6.28e-02   1.18e+00]
(1, 1.0)
[-0.02 -0.6   0.09  0.91]
(1, 1.0)
[-0.03 -0.41  0.1   0.65]
(0, 1.0)
[-0.04 -0.6   0.12  0.97]
(0, 1.0)
[-0.05 -0.8   0.14  1.3 ]
(1, 1.0)
[-0.06 -0.61  0.16  1.05]
(1, 1.0)

In [113]:
agent = Agent(.5, verbose=True)

In [1]:
from genetic import Generation
generation = Generation(10)

[2017-11-21 00:25:49,896] Making new env: CartPole-v0


In [12]:
generation.simulation_step()

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


[27.0, 36.0, 10.0, 9.0, 9.0, 15.0, 25.0, 9.0, 10.0, 10.0]

In [15]:
for agent in generation.agents:
    print(agent.reward)

0
0
0
0
0
0
0
0
0
0


In [14]:
generation.reset()

In [10]:
for agent in generation.agents:
    agent.reset()

In [27]:
generation.simulation(15)

403
[10.0, 9.0, 9.0, 10.0, 10.0, 124.0, 90.0, 25.0, 9.0, 41.0]
549
[294.0, 33.0, 42.0, 9.0, 10.0, 294.0, 42.0, 294.0, 294.0, 294.0]
394
[44.0, 483.0, 483.0, 483.0, 483.0, 483.0, 483.0, 483.0, 483.0, 483.0]
421
[614.0, 614.0, 614.0, 614.0, 614.0, 614.0, 614.0, 614.0, 614.0, 614.0]
62
[548.0, 548.0, 548.0, 548.0, 548.0, 548.0, 548.0, 548.0, 548.0, 548.0]
483
[627.0, 627.0, 627.0, 627.0, 627.0, 627.0, 627.0, 627.0, 627.0, 627.0]
567
[501.0, 501.0, 501.0, 501.0, 501.0, 501.0, 501.0, 501.0, 501.0, 501.0]
39
[482.0, 482.0, 482.0, 482.0, 482.0, 482.0, 482.0, 482.0, 482.0, 482.0]
37
[401.0, 401.0, 401.0, 401.0, 401.0, 401.0, 401.0, 401.0, 401.0, 401.0]
342
[492.0, 492.0, 492.0, 492.0, 492.0, 492.0, 492.0, 492.0, 492.0, 492.0]
116
[550.0, 550.0, 550.0, 550.0, 550.0, 550.0, 550.0, 550.0, 550.0, 550.0]
425
[523.0, 523.0, 523.0, 523.0, 523.0, 523.0, 523.0, 523.0, 523.0, 523.0]
453
[503.0, 503.0, 503.0, 503.0, 503.0, 503.0, 503.0, 503.0, 503.0, 503.0]
45
[558.0, 558.0, 558.0, 558.0, 558.0, 558.0, 5

In [5]:
rewards = [agent.reward for agent in generation.agents]

NameError: name 'generation' is not defined

In [118]:
agent = generation.agents[0]